env: HAPPYVER=1.19.12
language: haskell
ghc:
  - "8.6.5"
before_install:
  - cabal install happy-$HAPPYVER alex
  - cabal install --only-dependencies --enable-tests --allow-newer=test-fixture:template-haskell
script:
  - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
  - cabal build
  - cabal test
  - cabal check
